# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_payment', models.DateField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(max_length=10)),
                ('ward_no', models.CharField(max_length=3)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('municipal_vdc', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('duration', models.CharField(help_text='specify duration in weeks', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.CharField(help_text='eg:ds-001-2017, use py-python,dj-django,ds-datascience ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Ms', 'Ms')], max_length=5)),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('NA', 'Prefer Not To Say')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('qualification', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=14)),
                ('mobile_number', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Address')),
                ('course', models.ManyToManyField(to='mis.Course')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Student'),
        ),
    ]
