# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.BooleanField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestName', models.CharField(max_length=10)),
                ('MarksObtain', models.DecimalField(decimal_places=1, max_digits=4)),
                ('FullMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('PassMarks', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Absent', 'Absent'), ('Withheld', 'Withheld')], max_length=8)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cis.Exam')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mis.Student')),
            ],
        ),
    ]
